int64 id                             #pose number
float32[] o                          #robot origin
int64 o_w                            #origin vector width
int64 o_h                            #origin vector height
float32[] pos                        #robot current position
int64 pos_w                          #position vector width
int64 pos_h                          #position vector height
float64 yaw                          #robot orientation
float32[] k                          #robot to occupancy intrinsic parameters K
int64 k_w                            #K matrix width
int64 k_h                            #K matrix height
float32[] rt                         #robot to occupancy extrinsic parameters Rt
int64 rt_w                           #Rt matrix width
int64 rt_h                           #Rt matrix height
